---
micronaut:
  application:
    name: server

---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true
---
micronaut:
  router:
    static-resources:
      public:
        enabled: true
        paths: classpath:public