/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.pintowar;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.json.JsonHierarchicalStreamDriver;
import com.thoughtworks.xstream.security.AnyTypePermission;
import lombok.extern.slf4j.Slf4j;
import org.optaplanner.examples.pas.domain.PatientAdmissionSchedule;

import java.io.InputStream;

@Slf4j
public class DataGen {

    void experiment() {
        PatientAdmissionSchedule pas = readFromXml("data/xml/testdata01.xml");
        System.out.println(toJson(pas));
    }

    PatientAdmissionSchedule readFromXml(String xml) {
        InputStream in = this.getClass().getClassLoader().getResourceAsStream(xml);
        XStream xstream = new XStream();
        xstream.setMode(XStream.ID_REFERENCES);
        XStream.setupDefaultSecurity(xstream);
        xstream.processAnnotations(PatientAdmissionSchedule.class);

        xstream.addPermission(new AnyTypePermission());
        return (PatientAdmissionSchedule) xstream.fromXML(in);
    }

    String toJson(PatientAdmissionSchedule pas) {
        XStream xstream = new XStream(new JsonHierarchicalStreamDriver());
        xstream.setMode(XStream.ID_REFERENCES);

        return xstream.toXML(pas);
    }

    public static void main(String[] args) {
        new DataGen().experiment();
    }
}
