/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.2.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building an application
    application

    // Apply the groovy plugin to also add support for Groovy (needed for Spock)
    groovy
}

val optaplannerVersion = "7.17.0.Final"

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    implementation("org.optaplanner:optaplanner-core:$optaplannerVersion")
    implementation("org.optaplanner:optaplanner-examples:$optaplannerVersion") {
        exclude(group = "com.sun.xml.bind")
        exclude(group = "org.freemarker")
    }

    // Use the latest Groovy version for Spock testing
    testImplementation("org.codehaus.groovy:groovy:2.5.6")

    // Use the awesome Spock testing and specification framework even with Java
    testImplementation("org.spockframework:spock-core:1.2-groovy-2.5")
    testImplementation("junit:junit:4.12")
}

application {
    // Define the main class for the application
    mainClassName = "com.github.pintowar.App"
}
