/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.github.pintowar

import spock.lang.Specification

class DataGenTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new DataGen()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
